language: python

matrix:
  include:
    - language: python
      os: linux
      python: 3.7
      dist: bionic
      install:
        - sudo apt update
        - sudo apt -y install xvfb libmtdev-dev libgl1-mesa-dev libgles2-mesa-dev python3
        - python3 -m pip install pip wheel setuptools --upgrade
        - python3 -m pip install kivy --pre
      before_script:
        - export DISPLAY=:99.0
        - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1280x720x24 -ac +extension GLX
        - sleep 3
        - PYTHONPATH=.:$PYTHONPATH python3 -m pip install --editable .[dev,travis]
      script:
        - python3 -m pytest tests/ --cov kivy_garden/ --cov-branch
        - travis_retry coveralls
    - language: sh
      os: osx
      osx_image: xcode10.2
      before_install:
        - brew update
        - brew list python3 &>/dev/null || brew install python3
        - brew install pyenv-virtualenv
      install:
        - python3 -m pip install pip wheel setuptools --upgrade
        - python3 -m pip install kivy --pre
        - PYTHONPATH=.:$PYTHONPATH python3 -m pip install --editable .[dev,travis]
      script:
        - KIVY_GL_BACKEND=mock python3 -m pytest tests/ --cov kivy_garden/ --cov-branch
        - travis_retry coveralls
